IMB/Edx Python course notes
===========================

Course Notes for the IMB python short course

NOTE: IBM Cloud lite (free) accounts are ***deleted*** after 30 days of inactivity!

```{python}
print( "hello world" )
```

Before I finish this course:

- Get python working (maybe it needs to be running inside a conda environment?)
- Get python scripts executing from the command line

Module 1
--------

Python Basics: 

### types ###

Pretty straightforwards stuff.

integers, floats, strings and booleans.

You can make conversions between types - python is pretty clever - and can even convert strings to integers (assuming the string is an integer), like

```{python}
int('1')
```

Will convert '1', into the integer 1.

Floats to integers drops the decimal, and thus loses information.

You can't convert lettersa and symbols to ints (but what about ACII codes?)

Booleans are either true (1) or false (0).

### Expressions ###

Just basic operations.

Variable assignment

```{python}
my_variable = 1
my_variable:1 # will apparently 'denote' the variable, which I'm wondering how this is different from assignment??
```

More straightforward stuff.

### Strings ###

Each element in a string is indexed by integers, either positive or negative.

String operations are fairly intuitive.

    3 * x == xxx

You cannot 'add' a string, but you can add *to* a string.

`3 + x` -- returns an error

But `'3' + x` -- adds the number '3' to the string

Backslashes `\`, as usual are escape characters.

Slicing can be done using indexes.

```{python}
a = 'the cat in the hat '
a[::2] # Take every second character starting from one -- THIS IS A STRIDE VALUE
# 'tecti h a '
a[0:5:2] # Take from 0 to 5, and return every second character - this is slicing
# 'tec'

"345678".find('3') # Ah I see -- 'return index value of string '3'
```

Module 2
--------

### Lists and tuples ###

Tuples are ordered lists, defined by parentheses.

Tuples can be made of strings, integers, floats, etc. and any combination of these.

A tuple is always of type: tuple.

Tuples can be sliced and concatenated.

```{python}
tuple1 = (1,2,3,4)
tuple2 = ('cat','dog',5.3)

tuple1 + tuple2 = tuple3

tuple3 =  (1,2,3,4,'cat','dog',5.3)

tuple3[2:5]

# (3,4,'cat')

tuple4 = (5,3.2,9,"letter opener",tuple3)

tuple4[4][5][1]

# o

```

So tuples can be nested. Which is even more powerful than it sounds.

From what I can gather, this is the equivalent of creating a list in R.

We can index down to the atomic level, even within strings.

Lists are like tuples, but mutable.

```{python}

list1 = ["Michael Jackson", 10.1, 1982]

list1.extend(["pop", 10])

list1 = ["Michael Jackson", 10.1, 1982, "pop", 10]

list1.append(["pop", 10])

list1 = ["Michael Jackson", 10.1, 1982, "pop", 10, ["pop", 10]]

list1[3] = "soda"

list1 = ["Michael Jackson", 10.1, 1982, "soda", 10, ["pop", 10]]

del(list1[1])

list1 = ["Michael Jackson", 1982, "soda", 10, ["pop", 10]]

"hard rock".split()

# ["hard", "rock"]
# so \s is the default delimiter then?

"a,b,c,d".split(',')

# ["a","b","c","d"]

# I guess that answers my question

```

OK, interesting.

Aliasing.

```{python}
A=B

```

aliases A with B. When you change anything in list A, it changes in B too.

Cloning:

```{python}
B=A[:]
# Again, it is simply referencing all elements of A
```

This will create an independent clone of A: B. A change in A will not induce a change in A, because they are now independent.

A fellow student shared [this](https://stackabuse.com/lists-vs-tuples-in-python/) really interesting tutorial on lists vs tuples.

It's becoming increasingly evident that I should find other ways to practise coding, other than the labs here.

Python is obviously more complex than SQL, and the labs are quite simple.

### Data Structures ###

Sets area  type of collection

you can input types.

Sets are unordered

Only have unique elements (no duplicates!).

use curly brackets

```{python}

set1={'dog','cat','aardvark','mouse'}

```

You can convert lists to sets

```{python}
list8 = set(list1)
```

Can add to a set

```{python}
set1.add('tiger')
```

If we add an element that exists, nothign will happen.

Can check to see if an item is in a set:

```{python}
'cat' in set1
```

We can perform lots of mathematical operations in sets.

```{python}

set1={'dog','cat','aardvark','mouse'}

set2={'dog','mouse','elephant','sloth'}

```

For intersection we use `&`

This will find the common elements of each set.

```{python}

# intersection
set1 & set2

# {'dog','mouse'}

# union

set1.union(set2)

# check to find if a set is a subset of another

set1.issubset(set2)

# False

```

### Dictionaries ###

Dictionaries are like lists.

Except their indexes are not integers, but custom values, often characters or strings.

The syntax is as follows:

```{python}
dictionary1 = {"key":"value","key2":[1,2,3],"key3":"5",("key6"):5}
```

Nice to think of a dictionary as a two column table

key | variable

We can add to a dictionary

```{python}
dictionary1['key4']='(5,4)'

del(dictionary1['key4'])

'key' in dictionary1
# true

'key1' in dictionary1
# false

dictionary1.keys()

dictionary1.values()

```

Module 3
--------

Zooming along again. When did I start this? Was it Sunday or Saturday?

- lots of familiar content
- should really do some real coding
  - eh, finish the course first

1. conditions and branching
2. loops and functions
3. objects and classes

### Conditions and branching ###

Mostly just stuff on operators and conditionals.

If statements. syntax?

```{python}

if (age>18): # The brackets are not necessary!

  print("you can enter")

print("move on")

```


```{python}

age = 17

if (age>18): # The brackets are not necessary!

  print("you can enter")

print("move on")

```

```{python}

if (age>18): # The brackets are not necessary!

  print("you can enter")

else:

  print("go see Meatloaf")

print("move on")

```

```{python}

if (age>18): # The brackets are not necessary!

  print("you can enter")

elif(age==18):

  print("go see Pink Floyd")

else:

  print("go see Meatloaf")

print("move on")

```

Logic Operators

AND and OR booleans.

Pretty straightforward stuff.

```{python}

albumYear = 1970

if albumYear < 1980 and albumYear > 1969:
  print("This album was made in the 70's")

```

### Loops ###

`range()` generates number sequences based on its input

```{python}
range(3)
# [0,1,2]
range(10,15)
# [10,11,12,13,14]
```

for loops, exactly as they are in essentially any other language, at least the basic concept is the same.

```{python}
squares = ["red","yellow","green","purple","blue"]
for i in range(0,5):
  squares[i]="white"

# We can iterate directly on the list

for i in squares:
  i


for i in squares:
  squares[i]="white"

# enumerate can be used find the index and element in a list

for i,square in enumerate(squares):
  square
  i

```

while loops

```{python}

squares = ["orange","orange","orange","purple","orange"]
Newsquares=[]

i=0

while(squares[i]="orange"):

  Newsquares.append(squares[i])
  i=i+1

```

### Functions ###

Functions are functions.

example function:

```{python}

def add1(a):

  b=a+1

  return b

```

```{python}

def add1(a):
'''
this function takes an input, and adds '1' to it
'''
  b=a+1
  return b

help(add1)

```

```{python}

def mult(a,b):
  c=a*b
  return c

mult(3,8)

```

No returns...

```{python}

def MJ():
  print("Michael Jackson")

def NoWork():
  print(NoWork())

```

Multiple outputs

```{python}

def add2(a):
  b=a+1
  print(a, " plus 1 equals ", b)
  b

```

Loops in functions

```{python}

def printStuff(Stuff):
  for i,s in enumerate(Stuff):
    print("Album ", i, "'s rating is " , s)

```

Variadic parameters!

Variadic parameters accept a variable number of elements.

```{python}

def ArtistNames(*names):
  for name in names:
    print(name)

ArtistNames('leonardo','raphaelo')
# leonardo
# raphaelo
ArtistNames('leonardo','raphaelo','michaelangelo')
# leonardo
# raphaelo
# michaelangelo
ArtistNames('leonardo','raphaelo','michaelangelo','picasso')
# leonardo
# raphaelo
# michaelangelo
# picasso

```

Scope.

The scope of a variable, is the program space where that variable is accessible. A variable defined
outside of a function has a 'global scope', and is called a 'global variable'.

```{python}

def AddDC(x):
  x=x+"DC"
  print(x)
  return(x)

x="AC"
z=AddDC(x)

x
# 'AC'

print(AddDC(x))
# ACDC
# ACDC

```

Ah yeah, so we haven't given x a value yet, just declared it in the function. Then we assign it a value.
After this we can recruit it in the function?

Oh, I see now. 'x' has been globally defined as 'AC'.

In the function we've defined 'x' as 'ACDC', but this doesn't affect the global 'x' variable

- So you want to be *super* careful with how you define variables!

Python with first search withing the local scope for the variable value, and if it doesn't exist it will
check the global scope, and if it exists there, it will use that value.

You can also define a global variable in a function explicitly:

```{python}

def PinkFloyd():
  global ClaimedSales
  ClaimedSales="45 Million"
  return ClaimedSales

PinkFloyd()

print(ClaimedSales)

# What's a comment in jelleybeans - not bad, a bit more contrast than apprentice

```

### Objects and Classes ###

All data types are objects. All objects have:

- a type
- an internal data representation
- methods

an object is an instance of a particular type.

When we invoke an integer, we an invoking an 'int' object, which is of type 'int' (duh).

Methods are invoked by appending a period at the end of the object.

So, depending on the attributes of the object, some methods will work on it, some will not?

So a class is *kind of* like a function. So what's the difference exactly?

Class is a collection of objects, I think it's sinking in now. 

`5` is an element, or object, of `<class int>`
`dog` is an element, or object, of `<class str>`

So you can define your own class - so far as I can tell this means, you can create a particular set of characteristics, to which a set of objects can be described by, or defined by.

The followings are class members.

1. Class Attributes
2. Constructor
3. Instance Attributes
4. Properties
5. Class Methods

```{python}

class ThisisANewClass:
  <statement1>
  <statement2>
  ...
  <statementn>

```

So the fucken video starts off talking about integers being 'types', and I can't see anywhere, where it clarifies that 'type' is effectively the same as 'class'. Are they different?

So `sort()` is a method, but `type()` is a function? - just came to this realization doing some stuff in IDLE.

And so, according to some stack QnA, 'types' are basically builtins, and classes are user defined, but in this day and age there are no substantive differences. I suppose you can still think of types as builtin, and written in C, whearas classes are mostly user defined. But they now work the same way, and there is virtually no practical difference?

So now we're going to create our own classes 'circle' and 'rectangle'.

So, to make a circle, we need a radius. We can also add a colour, just to make things fancy.

so our attributes are 'radius' and 'color' (keeping it American).

Rectangle needs 'height' and 'width' and 'color'

```{python}

class Circle(object):

  def __init__(self,radius,color):
    self.radius = radius;
    self.color = color;

# __init__ is a constructor - this tells python you are making a new class (so it is sort of required to instantiate a class? Am I using 'instantiate' correctly here?

class Rectangle(object):

  def __init__(self,height,width,color):
    self.height = height;
    self.width = width;
    self.color = color;

```

```{python}

# Create a class
Redcircle = Circle(10,'red')
Redcircle
# <__main__.Circle object at 0x7fc1ec7a0550
# call the attributes
Redcircle.radius
# 10
Redcircle.color
# 'red'
C2 = Circle(5, 'blue')
C2.color
# 'blue'
# change the attribute directly
C2.color = 'green'
C2.color
# 'green'

```

Methods are functions which can change the attributes of the object.

```{python}

class Circle(object):

  def __init__(self,radius,color):
    self.radius = radius;
    self.color = color;

  def add_radius(self,r):
    self.radius=self.radius+r;

```

Phew. That video was intense.

> Functions *do* specific things, classes *are* specific things. 

From [this Stack Question](https://stackoverflow.com/questions/18202818/classes-vs-functions)

```{python}

class Circle(object):
  def __init__ (self, radius=3, color='blue'):
    self.radius = radius
    self.color = color
  def add_radius(self, r):
    self.radius = self.radius+r
    return(self.radius)
  def DrawCircle(self):
    plt.gca().add_patch(plt.Circle((0,0), radius = self.radius, fc=self.color))
    plt.axis('scaled')
    plt.show()

```

[//]: # ( This is taking too long - I need to work through the labs faster, and take note of what is difficult, and work on improving that later with practise )
[//]: # ( Man some Vim colorschemes are *weird!* )

[python exceptions](https://docs.python.org/3/library/exceptions.html) - looks useful!

```{python}
a = 1

try:
    b = int(input("Please enter a number to divide a"))
    a = a/b
    print("Success a=",a)
except ZeroDivisionError:
    print("The number you provided cant divide 1 because it is 0")
except ValueError:
    print("You did not provide a number")
except:
    print("Something went wrong")

```

Module 4
--------

Working with Data in python. OK, so we're getting onto the Data Science stuff now.

I think those last 2 modules went pretty quick and dirty through the basics. I wonder if a more extensive course will go a little slower through, and give you more time to build your intuition around a topic before hitting you with a heavy lab exercise?

### Reading files with open ###

Open function.

The second argument is the 'mode'

```{python}

file1 = open("path/to/file.txt","w")

# w = writing
# r = reading
# a = appending

```

Interesting.

    file1.name

Returns a string containing the file name "path/to/gile.txt"

    file1.mode

Indicates the mode 'w' for example.

'with' statement.

You can open a file, for a specific purpose, and then it closes when it is done:

```{python}

with open("path/to/file.txt","w") as file1:

  file_stuff = file1.read()
  print(file_stuff)

print(file1.closed)
print(file_stuff)

```

So, python can 'open' a file in read, write and append mode, but it can also store the contents of the file into an object. That's actually pretty cool.

I wonder if the use of loops is unintuitive to me, because I'm used to R parallelizing over everything.

I am starting to see how in python, everything is looped.

So basically, you can access and read files, and do lots of stuff to them.

I *really* need to do some real stuff with python, get used to doing this stuff.

Closing files at the end is very important!

> Using the with statement is better practice, it automatically closes the file even if the code encounters an exception. The code will run everything in the indent block then close the file object.

Yep, so can open the file, save the contents into an object, and then close it, and still have the contents in an object (duh).

But it means you probably like to read in a file, then perform changes to the saved object in python, then write the object to the old, or a new file.

### Writing ###

Can use method `.write` to write to file object.

```{python}

with open("path/to/file.txt", "w") as file1:

  file1.write("This is line A") # OK, so the 'r' and 'w' are basically the equivalent of read.data() and write() in R


lines = ["This is line A\n","This is line B\n","This is line C\n"]

with open("path/to/file2.txt", "w") as file2:

  for line in lines:
    File2.write(line)

# see this where I still get confused. What is with all this ambiguity? How does python know that 'line' represents a 'line in the file'. How often does it do this kind of thing? Are the other keywords that can be used in for loops to perform certain operations? Or am I just missing soemthig simple?


```

We can copy files too.

```{python}

with open("path/to/readfile","r") as readfile:
  with open("path/to/writefile","w") as writefile:
    for line in readfile:
      writefile.write(line)

```

Nice, now we're getting somewhere. `a+, w+, r+`.

So you can also 'control' the locatio of your 'cursor' in the file, using python.

```{python}

.tell()
.seek(offset,from)

```

### Loading Data with Pandas ###

OK, so this looks clearly designed to be familiar to R users.

```{python}
import pandas as pd

csv_path='path/to/file.csv'

df = pd.read_csv(csv_path)

# Can also do

excel_path='path/to/file.excel'

df = pd.read_excel(excel_path)

```

Creating a dataframe out of a dictionary

```{python}

songs = {'Album':['Thriller','Back in Black','the dark side of the moon'],
'Released':[1982,1980,1973],
'Lenght':['00:42:19','00:42:11','00:42:49']}

songs_frame = pd.DataFrame(songs)
```

```{python}

# Double Brackets.

x=df[['Artist','Length']]

# This will create a 'new' data frame, consisting of only the listed column/s

```

Ah they anticipated me. In the short data frame lab, I tried indexing on a specific value.

```{python}

df[1,1] # But it didn't work.

# You need to use a function loc, iloc or ix (loc - location), iloc - integer based location?

df.iloc[0,1]

```

OK, some cool stuff

```{python}

z=df.loc[0:2,'Artist':'Released'] # will select from column artist to column released - pretty clever

```

### Working with and saving data ###

```{python}

songs = {'Album':['Thriller','Back in Black','the dark side of the moon'],
'Released':[1982,1980,1973],
'Lenght':['00:42:19','00:42:11','00:42:49']}

df = pd.DataFrame(songs)

df['Released'].unique()

df['Released']>=1980

df1=df[df['Released']>=1980] # very much like R

df1.to_csv('path/to/newfile.csv')

```

### Numpy ###

```{python}

data import numpy as np

data=np.array([1,2,3,4,5])

```

Numpy arrays have attritubes:

```{python}

data.size # 5
data.ndim # 1
data.shape # (5,)

```

Working on the array

```{python}

c=np.array([2,5,4,7,23])

c[0]=20

c
# [20,5,4,7,23]

```

Operations

```{python}

u=np.array([0,1])
v=np.array([1,0])

w=u+v

w

# [1,1]

```

Yep, so operating on vectors in numpy is much simpler than base python, and apprently way faster (is is parallelised?)

I should learn/refresh more math and geometry.

sin waves are cool.

Wait, so what does `np.dot()` do? Need to look that up.

### Two Dimensional Numpy Arrays ###

```{python}

a = [[1, 2, 3], [11, 12, 13], [26, 27, 28]]

A = np.array(a) # Produces a 2d array (a matrix?)

A.ndim # 2

A.shape # (3,3)

A = np.array([0,1,1],[1,0,1])
B = np.array([1,1],[1,1],[-1,1])

C = np.dot(A,B);

```

Note: - A hadamard product of numpy arrays, is the same as what OpenMx calls a 'dot' product

From what I can tell, a dot product is not the same in python!

### APIs ###

Fucken sweet.

API - Application Programming Interface

You don't need to know how the API works. It has inputs, and outputs.

Makes sense. So an API for twitter allows you do bake-in to your site a tweet function which takes some piece of text (like a quote from an article) and inputs it as a tweet - probably takes your log in information, if you're logged it, and accesses the code to bring up a tweet box... or something to that effect.

Pandas is an API.

#### Rest APIs ####

RE - REpresentational
S - State
T - Transfer

Allow you to transfer across internet connections.

*Simple APIs transcript*

In this video, we will discuss Application Program Interfaces, API for short. Specifically, we will discuss what is an API, API libraries, REST API, including request and response. An API lets two pieces of software talk to each other. 

For example, you have your program, you have some data, you have other software components, you use the API to communicate with the API via inputs and outputs. Just like a function, you don't have to know how the API works but just as inputs and outputs. Pandas is actually a set of software components much of which are not even written in Python. 

You have some data. You have a set of software components. We use the pandas API to process the data by communicating with the other software components. 

Let's clean up the diagram. When you create a dictionary and then create a pandas object with a DataFrame constructor, in API lingo this is an instance. The data in the dictionary is passed along to the pandas API. 

You then use the DataFrame to communicate with the API. When you call the method head, the DataFrame communicates with the API displaying the first few rows of the DataFrame. When you call the method mean, the API will calculate the mean and return the values. 

REST APIs are another popular type of API. They allow you to communicate through the Internet allowing you to take advantage of resources like storage, access more data, artificial intelligent algorithms and much more. The RE stands for representational. 

The S stands for state. The T stands for transfer. In REST APIs, your program is called the client. 

The API communicates with a web service you call through the Internet. There is a set of rules regarding communication, input or request, and output or response. Here are some common terms. 

You or your code can be thought of as a client. The web service is referred to as a resource. The client finds the service via an endpoint. 

We will review this more in the next section. The client sends requests to the resource and the response to the client. HTTP methods are a way of transmitting data over the internet. 

We tell the REST APIs what to do by sending a request. The request is usually communicated via an HTTP message. The HTTP message usually contains a JSON file. 

This contains instructions for what operation we would like the service to perform. This operation is transmitted to the web service via the Internet. The service performs the operation. 

In the similar manner, the web service returns a response via an HTTP message, where the information is usually returned via JSON file. This information is transmitted back to the client. Sports data is always changing. 

This is an excellent application of an API as it can be constantly updated. We will use the `nba_api` by Swar Patel. The API is always being updated from endpoints at nba.com. 

Is simple to use, so you can focus on the task of collecting data. In the `nba_api`, to make request for a specific team, it's quite simple. We don't require a JSON file. 

All we require is an ID. This information is stored locally in the API. We import the module teams. 

The method `get_teams` returns a list of dictionaries, which have the same keys but the values depend on the team. The dictionary key id has a unique identifier for each team as a value. To make things easier, we can convert the dictionary to a table. 

First, we create the function `one_dict.` To create a dictionary, we use the common keys for each team as the keys. The value is a list. 

Each element of the list corresponds to the values for each team. We then convert the dictionary to a DataFrame. Each row contains the information for a different team. 

We'll use the teams nickname to find the unique ID. We can find the row that contains the warriors as follows. The ID is the first column. 

We can use the following line of code to access the first column of the DataFrame. We now have an integer that can be used to request the warriors information. The function Leaguegamefinder, will make an API call. 

The parameter `team_id_nullable` is the unique id for the warriors. Under the hood, the `nba_api` is making it an HTTP request. This is transmitted to nba.com. 

The information requested is provided and is transmitted via an HTTP response. This is assigned to the object gamefinder. The gamefinder object has a method `get_data_frame` that returns a data frame. 

If we view the DataFrame, we can see it contains information about all the games the warriors played. The `plus_minus` column contains information on the score. If the value is negative, the warriors lost by that many points. 

If the value is positive, the warriors won by that amount of points. The column match-up had the team the warriors were playing. GSW stands for Golden State and TOR means Toronto Raptors. 

Versus signifies it was a home game, and the @ symbol means an away game. We can create two DataFrames, one for the games where the warriors faced the raptors at home, and the second for away games. We can plot out the `plus_minus` column for both DataFrames. We see the warriors played better at home.

*Part 2*


In this video, we will discuss Application Program Interfaces that use some kind of artificial intelligence. We will transcribe an audio file using the Watson Text to Speech API. We will then translate the text to a new language using the Watson Language Translator API. 

In the API call, you will send a copy of the audio file to the API. This is sometimes called a POST request. Then the API will send the text transcription of what the individual is saying. 

Under the hood, the API is making a GET request. We then send the text we would like to translate into a second language to a second API. The API will translate the text and send the translation back to you. 

In this case, we translate English to Spanish. We then provide an overview of API keys and endpoints, Watson Speech to Text, and Watson Translate. First, we will review API keys and endpoints. 

They will give you access to the API. An API key as a way to access the API. It's a unique set of characters that the API uses to identify you and authorize you. 

Usually, your first call to the API includes the API key. This will allow you access to the API. In many APIs, you may get charged for each call. 

So like your password, you should keep your API key a secret. An endpoint is simply the location of the service. It's used to find the API on the Internet just like a web address. 

Now, we will transcribe an audio file using the Watson Text to Speech API. Before you start the lab, you should sign up for an API key. We will download an audio file into your directory. 

First, we import SpeechToTextV1 from IBM Watson. The service endpoint is based on the location of the service instance. We store the information in the variable `url_s2t.` To find out which URL to use, view the service credentials. 

You will do the same for your API key. You create a speech-to-text adapter object. The parameters are the endpoint and API key. 

You will use this object to communicate with the Watson Speech to Text service. We have the path of the wav file we would like to convert to text. We create the file object wav with the wav file using open. 

We set the mode to rb, which means to read the file in binary format. The file object allows us access to the wav file that contains the audio. We use the method recognize from the speech to text adapter object. 

This basically sends the audio file to Watson Speech to Text service. The parameter audio is the file object. The content type is the audio file format. 

The service sends a response stored in the object response. The attribute result contains a python dictionary. The key results value has a list that contains a dictionary. 

We are interested in the key transcript. We can assign it to the variable `recognized_text` as follows. `recognized_text` now contains a string with a transcribed text. 

Now let's see how to translate the text using the Watson Language Translator. First, we import LanguageTranslatorV3 from `ibm_watson.` We assign the service endpoint to the variable `url_l2.` You can obtain the service in the lab instructions. You require an API key, see the lab instructions on how to obtain the API key. 

This API request requires the date of the version, see the documentation. We create a language translator object, LanguageTranslator. We can get a list of the languages that the service can identify as follows. 

The method returns the language code. For example, English has a symbol en to Spanish, which has the symbol es. In the last section, we assigned the transcribed texts to the variable to `recognized_text.` We can use the method translate. 

This will translate the text. The result is a detailed response object. The parameter text is the text. 

`model_id` is the type of model we would like to use. In this case, we set it to en-es for English to Spanish. We use the method get result to get the translated text and assign it to the variable translation. 

The result is a dictionary that includes the translation word count and character count. We can obtain the translation and assign it to the variable `spanish_translation` as follows. Using the variable `spanish_translation`, we can translate the text back to English as follows. 

The result is a dictionary. We can obtain the string with the text as follows. We can then translate the text to French as follows. Thanks for watching this video.

Cool, so how do you do all this when you're not using an IBM account??

### HTTP ###

So, we've just briefly touched on HTTP. The obvious question is why is it important to add 5 minutes about this at the end of a python for data science course?

The obvious answer is that as a data scientist, one of the most broadly applicable ways of accessing data is publicly available data on the web. So it would be really important to have a least a vague familiarity with the process.

Makes me wonder if their are Edx courses that dig deeper into this, that go into good detail on how to mine the web for multiple types of publicly available data, and how to get a hold of it, and pull into a dataset?

It would be cool to know how to just surf the web for interesting data, and then know how to just pull it out whenever I wanted to.

So it's helpful to think of the Web Adress as just pointing you to a directory (server). Which I already know, it does help demystify it thought when I think of it that way (because that is what it is!).

What books/textbooks will help me understand all this further?
  - That old, deprecated HTML book probably has some stuff in it
  - I'll bet that RedHat, JavaScript and PhP books both have stuff in them too!

Check [this out](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

```{python}
# Definitely check this out
import requests

```

OK, some cool interesting stuff. Definitely check out the HTTP request lab again when you want to
play around with HTTP get, post and other requests in more detail.

[Lab as a gist](https://gist.github.com/DryLabRebel/efe0de292268bacb9742a295ca957c0a)

Cool.

Lutz, Mark. Learning Python: Powerful Object-Oriented Programming. " O'Reilly Media, Inc.", 2013.

[Introduction to Computer Science and Programming in Python](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/)

Maybe the MIT Open Python and Computer Science Course is my next step?

Going to have a crack at the final web scraping assignment too if I can

Code for Web Scraping from Final Assignment:

```{python}

def get_basketball_stats(link='https://en.wikipedia.org/wiki/Michael_Jordan'):
    # read the webpage 
    response = requests.get(link)
    # create a BeautifulSoup object to parse the HTML  
    soup = bs4.BeautifulSoup(response.text, 'html.parser')
    # the player stats are defined  with the attribute CSS class set to 'wikitable sortable'; 
    #therefore we create a tag object "table"
    table=soup.find(class_='wikitable sortable')

    #the headers of the table are the first table row (tr) we create a tag object that has the first row  
    headers=table.tr
    #the table column names are displayed  as an abbreviation; therefore we find all the abbr tags and returs an Iterator
    titles=headers.find_all("abbr")
    #we create a dictionary  and pass the table headers as the keys 
    data = {title['title']:[] for title in titles}
    #we will store each column as a list in a dictionary, the header of the column will be the dictionary key 

    #we iterate over each table row by fining each table tag tr and assign it to the objed
    for row in table.find_all('tr')[1:]:

        #we iterate over each cell in the table, as each cell corresponds to a different column we all obtain the correspondin key corresponding the column n 
        for key,a in zip(data.keys(),row.find_all("td")[2:]):
            # we append each elment and strip any extra HTML contnet 
            data[key].append(''.join(c for c in a.text if (c.isdigit() or c == ".")))

    # we remove extra rows by finding the smallest list     
    Min=min([len(x)  for x in data.values()])
    #we convert the elements in the key to floats 
    for key in data.keys():

        data[key]=list(map(lambda x: float(x), data[key][:Min]))

    return data
```

Have to make use of this somehow!


---

Useful functions:

```{python}

index()
len()
sorted()
add()
remove()

# sets logic
difference()
intersection()
union()
issubset()

```


